#configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/tennisapplication
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.main.allow-circular-references = true

server.servlet.session.timeout=30m

# --- Konfiguracja badan cache --
# server, http
app.cache.strategy=server
#caffeine, lru, fifo, redis (wazne tylko gdy powyzej "server")
app.cache.algorithm=redis

spring.data.redis.host=localhost
spring.data.redis.port=6379

#spring.jpa.show-sql=true
